# .github/workflows/deploy.yml
name: Deploy Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # Ensures deploy only happens if build and test jobs succeed
    strategy:
      matrix:
        service: [auth, todos, users]  # Service names for Auth API, TODOs API, and Users API

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and Deploy Docker Image
        run: |
          docker pull dieeju774/microservice-${{ matrix.service }}:latest
          docker run -d --name microservice-${{ matrix.service }} -p 8000:8000 dieeju774/microservice-${{ matrix.service }}:latest
